myfamily = ("mother","father","sister","brother","sister")
print(myfamily)
print(type(myfamily))
print(myfamily[-1])
print(myfamily[2])
y=list(myfamily)
y.append("me")
myfamily=tuple(y)
x=list(myfamily)
x.remove("brother")
myfamily=tuple(x)
print(myfamily)
x = int(input())
b = int(input())
